name: nubrick_flutter
description: "Nubrick bridge sdk for flutter"
version: 0.16.1
homepage: "https://nubrick.app"
repository: "https://github.com/plaidev/nubrick-flutter"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  stack_trace: ^1.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: app.nubrick.flutter.nubrick_flutter
        pluginClass: NubrickFlutterPlugin
      ios:
        pluginClass: NubrickFlutterPlugin
