name: "E2E Test - iOS"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-flutter-ios-e2e-app:
    runs-on: macos-15
    environment:
      name: Only Main
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: '16.2'

      - name: Run Xcode first launch tasks
        run: xcodebuild -runFirstLaunch

      - name: Install iOS Simulator runtime
        run: xcodebuild -downloadPlatform iOS

      - name: Set up Flutter
        uses: ./.github/actions/setup-flutter

      - name: Enable Swift Package Manager
        run: flutter config --enable-swift-package-manager
      - name: Build iOS
        working-directory: e2e
        run: flutter build ios --simulator

      - name: Zip app
        working-directory: e2e
        run: |
          cd build/ios/iphonesimulator && zip -r Runner.app.zip ./Runner.app

      - name: Upload to MagicPod
        working-directory: e2e
        run: |
          curl --fail-with-body -L -X POST \
            -F "file=@build/ios/iphonesimulator/Runner.app.zip" \
            -H "Authorization: Token ${{ secrets.MAGICPOD_API_TOKEN }}" \
            "https://app.magicpod.com/api/v1.0/Nativebrik.inc/Nativebrik-Flutter/upload-file/"
