name: "E2E Test - Android"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-android-e2e-app:
    runs-on: ubuntu-latest
    environment:
      name: Only Main
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup JDK
        uses: actions/setup-java@91d3aa4956ec4a53e477c4907347b5e3481be8c9 # v2.5.1
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Set up Flutter
        uses: ./.github/actions/setup-flutter

      - name: Build Android
        working-directory: e2e
        run: flutter build apk --debug

      - name: Upload e2e app
        working-directory: e2e
        run: |
          curl --fail-with-body -L -X POST \
            -F "file=@build/app/outputs/flutter-apk/app-debug.apk" \
            -H "Authorization: Token ${{ secrets.MAGICPOD_API_TOKEN }}" \
            "https://app.magicpod.com/api/v1.0/Nativebrik.inc/Nativebrik-Flutter/upload-file/"
